import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { Toaster } from "react-hot-toast";

import Providers from "@/redux/Providers";
import LoadUser from "@/components/LoadUser";

import "./globals.css";
import Link from "next/link";

// Configure the Poppins font correctly
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700", "800", "900"],
  variable: "--font-poppins-sans",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${poppins.variable}`}>
      <body className="antialiased">
        <Toaster position="top-center" />
        <Providers>
          <LoadUser>{children}</LoadUser>
        </Providers>
        <footer className="absolute bottom-0 w-full text-center text-white backdrop-blur-sm bg-black/40 py-2">
          <p>
            Made with ❤️ by{" "}
            <Link
              href="https://www.linkedin.com/in/pavan-kumar-mistry-5067b21b1/"
              className="text-white active:text-white underline"
            >
              Mistry Pavan Kumar
            </Link>
          </p>
        </footer>
      </body>
    </html>
  );
}
